// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDKWTijooxadYGwiDZyyt2mRUoCHVsyTA',
    appId: '1:721469780464:web:d9c542b900fbdeca9d2d35',
    messagingSenderId: '721469780464',
    projectId: 'popokarafriends',
    authDomain: 'popokarafriends.firebaseapp.com',
    storageBucket: 'popokarafriends.appspot.com',
    measurementId: 'G-K2YHB3MH6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPdngxw_czx-k2ge0C0bg0pfWElxaYL_o',
    appId: '1:721469780464:android:9ddd8e250ccb4a869d2d35',
    messagingSenderId: '721469780464',
    projectId: 'popokarafriends',
    storageBucket: 'popokarafriends.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmAwJhyG1KH2NULFp12hxvUVjNu_oVnkw',
    appId: '1:721469780464:ios:d14172ad5ca491599d2d35',
    messagingSenderId: '721469780464',
    projectId: 'popokarafriends',
    storageBucket: 'popokarafriends.appspot.com',
    iosBundleId: 'com.example.popofriendry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmAwJhyG1KH2NULFp12hxvUVjNu_oVnkw',
    appId: '1:721469780464:ios:d14172ad5ca491599d2d35',
    messagingSenderId: '721469780464',
    projectId: 'popokarafriends',
    storageBucket: 'popokarafriends.appspot.com',
    iosBundleId: 'com.example.popofriendry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDKWTijooxadYGwiDZyyt2mRUoCHVsyTA',
    appId: '1:721469780464:web:0d7a5f66502cbbc59d2d35',
    messagingSenderId: '721469780464',
    projectId: 'popokarafriends',
    authDomain: 'popokarafriends.firebaseapp.com',
    storageBucket: 'popokarafriends.appspot.com',
    measurementId: 'G-HHENXSF1F9',
  );
}
